export type IPost = {
  post_hint: string,
  preview: any,
  author: string,
  subreddit: string,
  score: number,
  saved: boolean,
  thumbnail: string,
  title: string,
  num_comments: number,
  name: string,
  media: any,
  author_fullname: string,
  link_flair_background_color: string,
  link_flair_text_color: string,
  link_flair_richtext: any,
  author_flair_background_color: string,
  author_flair_text_color: string,
  author_flair_richtext: any,
  spoiler: boolean,
  over_18: boolean,
  likes: boolean | null,
  url: string | null,
  archived: boolean,
  //img: string | null,
  permalink: string,
  selftext: string,
  selftext_html: string | null,
  gallery_data: any
}